### PR TITLE
Remove blank spaces left on the page after blocking replies

### PR DESCRIPTION
**Pull request by laike9m**
Inspired by #23 

|  **Before** | **After**  | 
|---|---|
|   |   |

### CODE REVIEW

**Comment by laike9m** [comment]
Kindly ping @slarkvan

**Comment by slarkvan** [comment]
> Kindly ping @slarkvan



> Kindly ping @slarkvan

 I previously attempted to write the CSS property “display:none” and it caused some inexplicable bugs when loading more replies in the reply list. I’m unsure if using the CSS property “height: 0” would also cause issues with loading more replies in the list. Could you please test this case locally?

**Comment by laike9m** [comment]
I've been using the locally modified version, and haven't spotted any issues so far. If you have a screenshot to show what the issue was like, I can help double check

**Comment by laike9m** [comment]
Thanks!

**Pull request merged**
